<a href="https://colab.research.google.com/github/AmitPrasad212003/Master-Data-Science-and-AI/blob/main/PythonForDA/15_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 style = "color : Brown">NumPy</h1>

- __NumPy__ is a Python library.
- It is used for working with arrays.
- It is short for "Numerical Python".
- It is used for computation and processing of single and multi dimensional array of elements.
- Smaller memory consumption and better runtime behavior.

In [ ]:
# To install the library

pip install numpy

import numpy

## Basic Operations

In [3]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
type(a)

numpy.ndarray

In [ ]:
a = np.array([1,2,3], dtype = float)
print(a)

[1. 2. 3.]


In [ ]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Get Dimensions of a numpy array
a.ndim

1

In [ ]:
#Get Dimensions of a numpy array
b.ndim

2

In [ ]:
c.ndim

2

In [ ]:
d = np.array([[[[1,2,3], [4,5,6], [7,8,9]]]])
print(d)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [ ]:
d.ndim

4

## Why Use NumPy?

- In Traditional Python Programming, we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to __50x__ faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.

## Time taken for the loop

In [ ]:
a

array([1., 2., 3.])

In [ ]:
#Get a shape of a numpy array
a.shape

(3,)

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.shape

(2, 3)

In [ ]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
c.shape

(3, 3)

In [ ]:
a

array([1., 2., 3.])

In [ ]:
a

array([1., 2., 3.])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a_int = np.array([1.1,2.1,3.4])
print(a_int)

[1.1 2.1 3.4]


In [ ]:
a_int.dtype

dtype('float64')

## Accessing/Changing specific elements, rows & columns etc.

In [ ]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a.ndim

2

In [ ]:
#Get a specific element [r,c]
a[0,3]

4

In [ ]:
a[1,0]

8

In [ ]:
a[1,5]

13

In [ ]:
#Get a specific row from a numpy array
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Get a specific column from a numpy array

a[:,0]

array([1, 8])

In [ ]:
#Get a specific column from a numpy array
a[:,0]

array([1, 8])

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
a[0,3] = 40
print(a)

[[ 1  2  3 40  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Change the 5th column in 1st row to 50
a[0,4] = 50

In [ ]:
a

array([[ 1,  2,  3, 40, 50,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

## Zeros/Ones method in NumPy

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((3,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.full((3,3), 50, dtype='float64')

array([[50., 50., 50.],
       [50., 50., 50.],
       [50., 50., 50.]])

In [ ]:
np.full((3,3), 50, dtype='int32')

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [ ]:
np.random.rand(4,4)

array([[0.75840089, 0.86087889, 0.1610105 , 0.39967769],
       [0.36738525, 0.16325008, 0.97694845, 0.47940924],
       [0.88013959, 0.48025697, 0.52094789, 0.79223042],
       [0.29775286, 0.06195496, 0.50064926, 0.94643265]])

In [ ]:
np.random.randint(-4,1, size=(3,3))

array([[-3,  0, -3],
       [-1, -1,  0],
       [ 0, -1, -2]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Practice Questions

## Question #1

Extract all the first 3 rows of the last 5 columns in a given numpy 2D array ‘a’?

In [ ]:
2,3,4,5,6
20,30,40,50,60
12,12,12,12,12

In [4]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

In [19]:
a[0 : 3,  1: ]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12, 12],
       [11, 21, 31, 41, 51, 61],
       [13, 24, 34, 44, 54, 64]])

In [ ]:
a[ :3 , -5: ]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])

## Question #2

Given a positive number 'n' greater than 2, create a NumPy array of size (nxn) with all zeros and ones such that the ones make a shape of "+"

Examples:

Input 1:

3

Output 1:

[[0 1 0]

 [1 1 1]

 [0 1 0]]

Input 2:

5

Output 1:

[[0 0 1 0 0]

 [0 0 1 0 0]

 [1 1 1 1 1]

 [0 0 1 0 0]

 [0 0 1 0 0]]

In [ ]:
n=5

In [ ]:
import numpy as np

# Create an (nxn) array with all zeros
z = np.zeros((n,n), dtype='int')
print(z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
# Make the middle row and column all 1s

z[n//2,:] = 1
z[:,n//2] = 1

# Print the final value of z
print(z)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


#### Just to help you understand about n//2

In [ ]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12, 12],
       [11, 21, 31, 41, 51, 61],
       [13, 24, 34, 44, 54, 64]])

In [ ]:
a[5//2,:]=1

In [ ]:
a[:,5//2]=1

In [ ]:
a

array([[ 1,  2,  1,  4,  5,  6],
       [10, 20,  1, 40, 50, 60],
       [ 1,  1,  1,  1,  1,  1],
       [11, 21,  1, 41, 51, 61],
       [13, 24,  1, 44, 54, 64]])

In [ ]:
a[5//2,:] = 1
print(a)

[[ 1  2  3  4  5  6]
 [10 20 30 40 50 60]
 [ 1  1  1  1  1  1]
 [11 21 31 41 51 61]
 [13 24 34 44 54 64]]


In [ ]:
a[:,n//2] = 1
print(a)

[[ 1  2  1  4  5  6]
 [10 20  1 40 50 60]
 [ 1  1  1  1  1  1]
 [11 21  1 41 51 61]
 [13 24  1 44 54 64]]


## Arithmetic Operations with NumPy - Maths + Stats

In [ ]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a+2

array([3, 4, 5, 6])

In [ ]:
#DO it for -, /, *, //, ** - ALmost all the operations are satisfied

a**3

array([ 1,  8, 27, 64], dtype=int32)

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.min()

1

In [ ]:
np.min(a)

1

In [ ]:
a.max()

4

In [ ]:
np.max(a)

4

In [ ]:
a.mean()

2.5

In [ ]:
np.mean(a)

2.5

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.max(a)

8

In [ ]:
a.max()

8

In [ ]:
np.min(a)

1

In [ ]:
np.mean(a)

4.5

In [ ]:
np.sum(a)

36

In [ ]:
np.max(a, axis=1)

array([4, 8])

In [ ]:
np.max(a, axis=0)

array([5, 6, 7, 8])

In [ ]:
np.min(a, axis=0)

array([1, 2, 3, 4])

In [ ]:
np.min(a, axis=1)

array([1, 5])

In [ ]:
np.sum(a, axis=1)

array([10, 26])

In [ ]:
np.sum(a, axis=0)

array([ 6,  8, 10, 12])